annotations:
  licenses: Apache-2.0
apiVersion: v2
appVersion: "18.1"
description: This PostgreSQL cluster solution includes the PostgreSQL replication
  manager, an open-source tool for managing replication and failover on PostgreSQL
  clusters.
icon: https://dyltqmyl993wv.cloudfront.net/assets/stacks/postgresql/img/postgresql-stack-220x234.png
keywords:
- postgresql
- repmgr
- pgpool
- postgres
- database
- sql
- replication
- cluster
- high availability
maintainers:
- email: raymondstrose@hotmail.com
  name: Raymond St.Rose
name: postgresql-ha
version: 0.0.8
